/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    news: News;
    "news-sections": NewsSection;
    reviews: Review;
    verticals: Vertical;
    "bonus-offers": BonusOffer;
    "help-directory-entries": HelpDirectoryEntry;
    authors: Author;
    "site-users": SiteUser;
    comments: Comment;
    "reader-reviews": ReaderReview;
    "forum-threads": ForumThread;
    "forum-replies": ForumReply;
    notifications: Notification;
    media: Media;
    users: User;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    "news-sections": NewsSectionsSelect<false> | NewsSectionsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    verticals: VerticalsSelect<false> | VerticalsSelect<true>;
    "bonus-offers": BonusOffersSelect<false> | BonusOffersSelect<true>;
    "help-directory-entries": HelpDirectoryEntriesSelect<false> | HelpDirectoryEntriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    "site-users": SiteUsersSelect<false> | SiteUsersSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    "reader-reviews": ReaderReviewsSelect<false> | ReaderReviewsSelect<true>;
    "forum-threads": ForumThreadsSelect<false> | ForumThreadsSelect<true>;
    "forum-replies": ForumRepliesSelect<false> | ForumRepliesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    faq: Faq;
    "legal-documents": LegalDocument;
    "market-stats": MarketStat;
  };
  globalsSelect: {
    faq: FaqSelect<false> | FaqSelect<true>;
    "legal-documents": LegalDocumentsSelect<false> | LegalDocumentsSelect<true>;
    "market-stats": MarketStatsSelect<false> | MarketStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  /**
   * Structural article-type taxonomy. Matches the FilterChips on /categories/[slug] pages. Fixed enum — not records, per the deliberate design note in site-data.ts:67.
   */
  type: "guide" | "analysis" | "research" | "blog";
  /**
   * The domain this article is about. Independent from type — an article has both a type (Guide) and a vertical (Sportsbooks).
   */
  vertical: number | Vertical;
  author: number | Author;
  status: "draft" | "published";
  /**
   * Real Date. Frontend formats for display. Only set when status transitions to published — enforce with a beforeChange hook so publishedAt cannot be manually set to a future or fake date.
   */
  publishedAt?: string | null;
  /**
   * Auto-maintained by Payload. Use for the "updated" line on the article page when it differs from publishedAt.
   */
  updatedAt: string;
  /**
   * Standalone summary. Used in listings, search excerpts, and card previews. NEVER used as the SEO metaDescription — those are separate fields to prevent the byline-as-description bug.
   */
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Required. blog/[slug]/page.tsx:92 TODO flags the hero image as required with figcaption credit — this enforces it at the schema level.
   */
  heroImage: number | Media;
  /**
   * Figcaption/credit line for the hero image.
   */
  heroImageCredit?: string | null;
  /**
   * Optional. Short bullet takeaways rendered at the top of the article.
   */
  takeaways?:
    | {
        takeaway: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Related articles for the sidebar/rail. Deliberate curation — not an auto-generated "you might also like." Manual selection is what makes the cluster-linking strategy work.
   */
  related?: (number | Article)[] | null;
  seo: {
    /**
     * Written specifically for this page. Do not leave empty and rely on a frontend default — that fallback pattern is exactly what produced the homepage-title bug on review pages.
     */
    metaTitle: string;
    /**
     * A real summary of this specific page, not derived from a byline or excerpt string. Byline-as-description was one of the shipped bugs.
     */
    metaDescription: string;
    /**
     * Leave blank in almost all cases. Canonical URL is derived from the record's slug at render. Only set this for deliberate cross-references.
     */
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verticals".
 */
export interface Vertical {
  id: number;
  /**
   * Display name, e.g. "Online Casinos", "Esports Betting". Used everywhere the vertical is rendered.
   */
  name: string;
  /**
   * URL segment. Used for both /categories/[slug] and — when hasReviews — /reviews/[slug]. Never store an href; derive at render.
   */
  slug: string;
  /**
   * Singular word used in running copy, e.g. "sportsbook", "casino", "operator". Carried over from ReviewGroup.noun.
   */
  noun: string;
  /**
   * Short breadcrumb label. Often the same as name, but a longer name might get shortened here.
   */
  crumb: string;
  /**
   * Short body copy for the /categories/[slug] landing page — one or two sentences describing the vertical.
   */
  description: string;
  /**
   * When true, a /reviews/[slug] route is generated for this vertical. When false, only /categories/[slug] exists. This is the subset marker that replaces the separate ReviewGroup list.
   */
  hasReviews?: boolean | null;
  /**
   * Explicit ordering across verticals. Replaces the array-order dependency in site-data.ts.
   */
  order: number;
  seo: {
    /**
     * Written specifically for this page. Do not leave empty and rely on a frontend default — that fallback pattern is exactly what produced the homepage-title bug on review pages.
     */
    metaTitle: string;
    /**
     * A real summary of this specific page, not derived from a byline or excerpt string. Byline-as-description was one of the shipped bugs.
     */
    metaDescription: string;
    /**
     * Leave blank in almost all cases. Canonical URL is derived from the record's slug at render. Only set this for deliberate cross-references.
     */
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required. Every rendered image must have alt text for accessibility and schema.org. Empty alt is a violation of both, not a UX choice — enforce at schema level so a content author cannot skip it.
   */
  alt: string;
  /**
   * Optional photo credit / attribution. Rendered as figcaption on hero images per the blog/[slug]/page.tsx:92 TODO.
   */
  credit?: string | null;
  /**
   * Optional caption text, separate from the credit line.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Full name as it appears in bylines and on the author page.
   */
  name: string;
  /**
   * URL segment for /authors/[slug]. Never store an href; derive at render.
   */
  slug: string;
  /**
   * Short line describing the author's beat and credential, e.g. "Lead reviews analyst · covers withdrawal infrastructure". Appears in bylines and on the author page.
   */
  credentialLine: string;
  /**
   * Author photo. Required — schema.org Person needs an image for Article structured data, and ArticleByline.tsx:11 states a real Person record must exist for an article to publish.
   */
  photo: number | Media;
  /**
   * Long-form bio for the author page. Optional — the credentialLine covers the byline surface.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Topics this author covers. TODO in authors/[slug]/page.tsx:37 notes these become links once an author-filtered archive exists.
   */
  beats?:
    | {
        beat?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Editorial standards this author holds themselves to. Rendered on the author page. Kept per-author rather than sitewide because different authors cover different beats with different applicable standards.
   */
  standards?:
    | {
        standard?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * External profile URLs for schema.org Person sameAs. LinkedIn, Twitter/X, personal site, etc. TODO at authors/[slug]/page.tsx:110 flags this as required for full Person JSON-LD.
   */
  sameAs?:
    | {
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck instead of deleting when an author leaves — preserves attribution on their existing published work.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL segment for the story. Combined with section.slug at render: /news/[section-slug]/[story-slug].
   */
  slug: string;
  /**
   * The parent section grouping. Maps to the /news/[section] route level.
   */
  section: number | NewsSection;
  /**
   * News beat taxonomy — separate from Verticals. "Esports" here is a news beat; "Esports Betting" is a vertical. Similar names, deliberately different meanings.
   */
  beat: "regulation" | "markets" | "business" | "product" | "esports" | "sports";
  author: number | Author;
  status: "draft" | "published";
  /**
   * Real Date. sectionSummary() in news.ts derives "N stories · latest <date>" from array order — publishedAt as a real date makes that a query, not a positional guess.
   */
  publishedAt?: string | null;
  /**
   * Standalone. Used as feed dek and story standfirst.
   */
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroImage: number | Media;
  heroImageCredit?: string | null;
  /**
   * Per-story takeaways. The current frontend has one shared newsStoryTakeaways array across all stories — this schema fixes that by making them per-record.
   */
  takeaways?:
    | {
        takeaway: string;
        id?: string | null;
      }[]
    | null;
  /**
   * External sources cited in the story. TODO at news/[slug]/[story]/page.tsx:148 flags this as required for the sources section — enforcing it at the schema level.
   */
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seo: {
    /**
     * Written specifically for this page. Do not leave empty and rely on a frontend default — that fallback pattern is exactly what produced the homepage-title bug on review pages.
     */
    metaTitle: string;
    /**
     * A real summary of this specific page, not derived from a byline or excerpt string. Byline-as-description was one of the shipped bugs.
     */
    metaDescription: string;
    /**
     * Leave blank in almost all cases. Canonical URL is derived from the record's slug at render. Only set this for deliberate cross-references.
     */
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-sections".
 */
export interface NewsSection {
  id: number;
  name: string;
  slug: string;
  /**
   * One or two sentences on what this section covers. Rendered on the /news/[section] landing page.
   */
  description: string;
  order: number;
  seo: {
    /**
     * Written specifically for this page. Do not leave empty and rely on a frontend default — that fallback pattern is exactly what produced the homepage-title bug on review pages.
     */
    metaTitle: string;
    /**
     * A real summary of this specific page, not derived from a byline or excerpt string. Byline-as-description was one of the shipped bugs.
     */
    metaDescription: string;
    /**
     * Leave blank in almost all cases. Canonical URL is derived from the record's slug at render. Only set this for deliberate cross-references.
     */
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * Operator name as displayed.
   */
  name: string;
  slug: string;
  /**
   * Which vertical this operator belongs to. Only verticals with hasReviews: true should be selectable — enforce with a filterOptions callback.
   */
  vertical: number | Vertical;
  /**
   * The analyst who authored this review. Byline is derived from this relationship at render, never stored as a formatted string.
   */
  author: number | Author;
  /**
   * Flip to "Needs re-verification" once the retest window passes. lastVerified's bracketed placeholder in the current frontend is a symptom of this field being absent.
   */
  status: "draft" | "published" | "needs-reverification";
  /**
   * Overall score. See categoryScores below for the breakdown that makes this up.
   */
  score: number;
  /**
   * D1: must be checked before publishing. This is the data-layer enforcement of "we test with real money" — the editorial promise becomes a schema constraint. A beforeChange hook (later handoff) should block status: published while this is false. The publish button in the admin UI can also gate on it.
   */
  fundedAccountConfirmed: boolean;
  /**
   * Per-criterion score breakdown. Currently the frontend stores label as free text (lib/types.ts) — this schema replaces that with a required label field per row. If we later introduce a shared RubricCriteria collection, this becomes a relationship instead. For now, freeform label with a strict schema is the honest incremental step.
   */
  categoryScores: {
    label: string;
    score: number;
    id?: string | null;
  }[];
  /**
   * Short bullets displayed on ranked rows and used as the search excerpt fallback.
   */
  advantages: {
    advantage: string;
    id?: string | null;
  }[];
  /**
   * Optional. Rendered on the full review page in ProsConsSection.
   */
  pros?:
    | {
        pro: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Rendered on the full review page in ProsConsSection.
   */
  cons?:
    | {
        con: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Real Date, not a display string. Frontend formats for display. The bracketed placeholder in the current frontend was a symptom of this being a string field.
   */
  lastVerified: string;
  /**
   * Bonus terms line — brief text summarising terms of any current bonus.
   */
  terms?: string | null;
  /**
   * When true, this review renders a PrimaryDomainLink instead of an operator link. Enforcement that only one review per rendered list has this true is at the query/render layer, not the schema — flag for the frontend audit.
   */
  isPrimaryDomain?: boolean | null;
  /**
   * Only populated when isPrimaryDomain is true. This is the only outbound link on the site where relAttribute is editable.
   */
  primaryDomainLink?: {
    anchorText: string;
    url: string;
    /**
     * Only editable on primary domain links. Operator links never have this field — the asymmetry is structural. Dofollow should be a deliberate editorial decision, never a default.
     */
    relAttribute: "nofollow" | "sponsored" | "dofollow";
  };
  /**
   * The outbound link to the operator being reviewed. Never has a relAttribute field — rel is forced to "nofollow sponsored" at the render layer. Making this a structural absence rather than a default preserves the safety property from lib/types.ts.
   */
  operatorLink?: {
    anchorText: string;
    url: string;
  };
  reviewBody: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo: {
    /**
     * Written specifically for this page. Do not leave empty and rely on a frontend default — that fallback pattern is exactly what produced the homepage-title bug on review pages.
     */
    metaTitle: string;
    /**
     * A real summary of this specific page, not derived from a byline or excerpt string. Byline-as-description was one of the shipped bugs.
     */
    metaDescription: string;
    /**
     * Leave blank in almost all cases. Canonical URL is derived from the record's slug at render. Only set this for deliberate cross-references.
     */
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bonus-offers".
 */
export interface BonusOffer {
  id: number;
  /**
   * Internal name for the offer, e.g. "Peak Wager welcome bonus June 2026".
   */
  name: string;
  /**
   * The operator this offer belongs to. Optional only if isPrimaryDomain is true (sitewide primary domain offer).
   */
  operator?: (number | null) | Review;
  /**
   * When true, this is the primary domain offer. Only one should be active at a time — enforce at render, not schema.
   */
  isPrimaryDomain?: boolean | null;
  /**
   * Short display headline for the offer, e.g. "100% match up to $500".
   */
  headline: string;
  /**
   * Promo code, if any. Optional.
   */
  code?: string | null;
  /**
   * Optional benefit bullets displayed under the offer.
   */
  benefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  primaryDomainLink?: {
    anchorText: string;
    url: string;
    relAttribute: "nofollow" | "sponsored" | "dofollow";
  };
  /**
   * No relAttribute — forced to nofollow sponsored at render. Structural safety, same as Reviews.
   */
  operatorLink?: {
    anchorText: string;
    url: string;
  };
  validFrom?: string | null;
  /**
   * When the offer expires. Frontend should hide expired offers automatically — flag for the frontend audit.
   */
  validUntil?: string | null;
  /**
   * Manual on/off. When false, the offer is hidden regardless of validUntil.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-directory-entries".
 */
export interface HelpDirectoryEntry {
  id: number;
  /**
   * The organisation name.
   */
  name: string;
  /**
   * ISO 3166-1 alpha-2 code, e.g. "IE", "US", "GB".
   */
  country: string;
  /**
   * Region grouping for the directory listing. Kept as enum rather than a separate Regions collection — regions rarely change and don't carry their own content.
   */
  region:
    | "north-america"
    | "uk-ireland"
    | "europe"
    | "asia-pacific"
    | "latin-america"
    | "middle-east-africa";
  description: string;
  /**
   * Contact routes. At least one must be present — enforced at hook level.
   */
  contacts?: {
    phone?: string | null;
    website?: string | null;
    /**
     * URL to a chat/messaging service, e.g. text line, WhatsApp, live chat.
     */
    chat?: string | null;
  };
  /**
   * Set to true only after manually verifying the organisation is real and its contact routes are current. CLAUDE.md rule 3: unverified entries render as "coming soon" placeholders, not as if they were real.
   */
  verified: boolean;
  /**
   * When this entry was last verified. Should be re-verified periodically. If old, treat as suspect.
   */
  verifiedAt?: string | null;
  /**
   * Only settable when verified is true (enforced by hook). Crisis lines are treated specially — they must never render as a placeholder or unverified, because the surface promises real crisis support.
   */
  isCrisisLine?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-users".
 */
export interface SiteUser {
  id: number;
  email: string;
  username: string;
  /**
   * Display name. Optional — username is required, name is the "as it appears in real life" version.
   */
  name?: string | null;
  /**
   * Per-user commenting reputation. Trusted bypasses the moderation queue after enough clean history. Banned blocks new submissions.
   */
  moderationStatus: "normal" | "trusted" | "flagged" | "banned";
  /**
   * Auto-maintained by hooks on Comments and ReaderReviews.
   */
  moderationHistory?: {
    commentsApproved?: number | null;
    commentsRejected?: number | null;
    readerReviewsApproved?: number | null;
    readerReviewsRejected?: number | null;
  };
  /**
   * Populated once auth is wired. When using Clerk, this is the Clerk user ID. When using Payload built-in auth, this stays null and Payload handles identity directly. Keeping this field means the auth decision does not require a schema migration later.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  author: number | SiteUser;
  targetType: "reviews" | "articles" | "news";
  /**
   * ID of the target content. Stored as text + targetType (polymorphic) rather than a union relationship — cleaner than a Payload union field for this shape.
   */
  targetId: string;
  /**
   * For threaded replies. Null for top-level comments. Frontend enforces max depth at render.
   */
  parentComment?: (number | null) | Comment;
  /**
   * Plain text only. URLs auto-linked at render with rel="nofollow noopener noreferrer" forced. Never render raw HTML from this field.
   */
  body: string;
  /**
   * beforeChange hook forces pending on create. Spam is a terminal silent state — no notification sent.
   */
  status: "pending" | "approved" | "rejected" | "edited" | "spam";
  /**
   * When a moderator approves-with-edits, the edited version goes here. Public render uses editedBody when present, falls back to body. Original body preserved for audit.
   */
  editedBody?: string | null;
  moderation?: {
    moderatedBy?: (number | null) | SiteUser;
    moderatedAt?: string | null;
    rejectionReason?:
      | (
          | "off-topic"
          | "promotional"
          | "harassment"
          | "duplicate"
          | "suspected-spam"
          | "responsible-gambling"
          | "other"
        )
      | null;
    additionalContext?: string | null;
    /**
     * Moderator-only notes. Never rendered publicly — enforce at the API/render layer, not just by convention.
     */
    internalNotes?: string | null;
  };
  notificationSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reader-reviews".
 */
export interface ReaderReview {
  id: number;
  /**
   * The reader submitting the review. Never editable — changing authorship silently is a moderation-integrity issue.
   */
  author: number | SiteUser;
  /**
   * The operator being reviewed. Combined with author, forms the uniqueness constraint — one reader-review per user per operator.
   */
  operator: number | Review;
  /**
   * Rating value that feeds AggregateRating. Making this required and bounded is what makes CLAUDE.md rule 4 possible — AggregateRating can only be computed from real moderated reviews with a rating value, so the value has to actually exist on the record.
   */
  rating: number;
  /**
   * Plain text. Same principle as Comments — no HTML surface.
   */
  body: string;
  /**
   * Forced to pending on create by a beforeChange hook. Only approved reader-reviews contribute to AggregateRating.
   */
  status: "pending" | "approved" | "rejected" | "spam";
  moderation?: {
    moderatedBy?: (number | null) | SiteUser;
    moderatedAt?: string | null;
    rejectionReason?:
      | ("off-topic" | "not-customer" | "promotional" | "harassment" | "suspected-spam" | "other")
      | null;
    additionalContext?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-threads".
 */
export interface ForumThread {
  id: number;
  title: string;
  slug: string;
  author: number | SiteUser;
  /**
   * Plain text, same principle as Comments. No rich text on user-generated content.
   */
  body: string;
  /**
   * Optional — link a thread to the review it discusses. Lets review pages surface real reader pushback as a trust signal.
   */
  relatedReview?: (number | null) | Review;
  status: "pending" | "open" | "locked" | "flagged" | "spam";
  /**
   * Auto-maintained by an afterChange hook on ForumReplies.
   */
  replyCount?: number | null;
  lastActivityAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-replies".
 */
export interface ForumReply {
  id: number;
  thread: number | ForumThread;
  author: number | SiteUser;
  body: string;
  /**
   * For nested replies. Frontend enforces max depth at render.
   */
  parentReply?: (number | null) | ForumReply;
  flagged?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | SiteUser;
  type:
    | "comment-approved"
    | "comment-edited"
    | "comment-rejected"
    | "reader-review-approved"
    | "reader-review-rejected"
    | "comment-reply";
  title: string;
  body: string;
  relatedComment?: (number | null) | Comment;
  relatedReaderReview?: (number | null) | ReaderReview;
  /**
   * Recipient can flip this. Verify session ownership on write — never let a user mark someone else's notification.
   */
  read?: boolean | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "articles";
        value: number | Article;
      } | null)
    | ({
        relationTo: "news";
        value: number | News;
      } | null)
    | ({
        relationTo: "news-sections";
        value: number | NewsSection;
      } | null)
    | ({
        relationTo: "reviews";
        value: number | Review;
      } | null)
    | ({
        relationTo: "verticals";
        value: number | Vertical;
      } | null)
    | ({
        relationTo: "bonus-offers";
        value: number | BonusOffer;
      } | null)
    | ({
        relationTo: "help-directory-entries";
        value: number | HelpDirectoryEntry;
      } | null)
    | ({
        relationTo: "authors";
        value: number | Author;
      } | null)
    | ({
        relationTo: "site-users";
        value: number | SiteUser;
      } | null)
    | ({
        relationTo: "comments";
        value: number | Comment;
      } | null)
    | ({
        relationTo: "reader-reviews";
        value: number | ReaderReview;
      } | null)
    | ({
        relationTo: "forum-threads";
        value: number | ForumThread;
      } | null)
    | ({
        relationTo: "forum-replies";
        value: number | ForumReply;
      } | null)
    | ({
        relationTo: "notifications";
        value: number | Notification;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "users";
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  vertical?: T;
  author?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  excerpt?: T;
  body?: T;
  heroImage?: T;
  heroImageCredit?: T;
  takeaways?:
    | T
    | {
        takeaway?: T;
        id?: T;
      };
  related?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
      };
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  section?: T;
  beat?: T;
  author?: T;
  status?: T;
  publishedAt?: T;
  excerpt?: T;
  body?: T;
  heroImage?: T;
  heroImageCredit?: T;
  takeaways?:
    | T
    | {
        takeaway?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-sections_select".
 */
export interface NewsSectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  vertical?: T;
  author?: T;
  status?: T;
  score?: T;
  fundedAccountConfirmed?: T;
  categoryScores?:
    | T
    | {
        label?: T;
        score?: T;
        id?: T;
      };
  advantages?:
    | T
    | {
        advantage?: T;
        id?: T;
      };
  pros?:
    | T
    | {
        pro?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        con?: T;
        id?: T;
      };
  lastVerified?: T;
  terms?: T;
  isPrimaryDomain?: T;
  primaryDomainLink?:
    | T
    | {
        anchorText?: T;
        url?: T;
        relAttribute?: T;
      };
  operatorLink?:
    | T
    | {
        anchorText?: T;
        url?: T;
      };
  reviewBody?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verticals_select".
 */
export interface VerticalsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  noun?: T;
  crumb?: T;
  description?: T;
  hasReviews?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bonus-offers_select".
 */
export interface BonusOffersSelect<T extends boolean = true> {
  name?: T;
  operator?: T;
  isPrimaryDomain?: T;
  headline?: T;
  code?: T;
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  primaryDomainLink?:
    | T
    | {
        anchorText?: T;
        url?: T;
        relAttribute?: T;
      };
  operatorLink?:
    | T
    | {
        anchorText?: T;
        url?: T;
      };
  validFrom?: T;
  validUntil?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-directory-entries_select".
 */
export interface HelpDirectoryEntriesSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  region?: T;
  description?: T;
  contacts?:
    | T
    | {
        phone?: T;
        website?: T;
        chat?: T;
      };
  verified?: T;
  verifiedAt?: T;
  isCrisisLine?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  credentialLine?: T;
  photo?: T;
  bio?: T;
  beats?:
    | T
    | {
        beat?: T;
        id?: T;
      };
  standards?:
    | T
    | {
        standard?: T;
        id?: T;
      };
  sameAs?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-users_select".
 */
export interface SiteUsersSelect<T extends boolean = true> {
  email?: T;
  username?: T;
  name?: T;
  moderationStatus?: T;
  moderationHistory?:
    | T
    | {
        commentsApproved?: T;
        commentsRejected?: T;
        readerReviewsApproved?: T;
        readerReviewsRejected?: T;
      };
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  author?: T;
  targetType?: T;
  targetId?: T;
  parentComment?: T;
  body?: T;
  status?: T;
  editedBody?: T;
  moderation?:
    | T
    | {
        moderatedBy?: T;
        moderatedAt?: T;
        rejectionReason?: T;
        additionalContext?: T;
        internalNotes?: T;
      };
  notificationSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reader-reviews_select".
 */
export interface ReaderReviewsSelect<T extends boolean = true> {
  author?: T;
  operator?: T;
  rating?: T;
  body?: T;
  status?: T;
  moderation?:
    | T
    | {
        moderatedBy?: T;
        moderatedAt?: T;
        rejectionReason?: T;
        additionalContext?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-threads_select".
 */
export interface ForumThreadsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  body?: T;
  relatedReview?: T;
  status?: T;
  replyCount?: T;
  lastActivityAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-replies_select".
 */
export interface ForumRepliesSelect<T extends boolean = true> {
  thread?: T;
  author?: T;
  body?: T;
  parentReply?: T;
  flagged?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  body?: T;
  relatedComment?: T;
  relatedReaderReview?: T;
  read?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * FAQ entries. Order here determines rendered order on /faq.
   */
  entries: {
    question: string;
    /**
     * The answer text. Should summarise the source content, not duplicate it in full — the linked source is the canonical version.
     */
    answer: string;
    /**
     * Only published entries appear in FAQPage JSON-LD.
     */
    status: "draft" | "published";
    /**
     * Optional link to the full source content that this entry summarises. Prevents answer-vs-source drift by making the source explicit.
     */
    sourceLink?: {
      label?: string | null;
      href?: string | null;
    };
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents".
 */
export interface LegalDocument {
  id: number;
  /**
   * The four legal documents.
   */
  documents: {
    slug: "privacy-policy" | "terms-of-service" | "affiliate-disclosure" | "cookie-policy";
    title: string;
    intro: string;
    /**
     * Also used as the search excerpt for this legal doc.
     */
    summary: string;
    sections: {
      heading: string;
      body: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ("ltr" | "rtl") | null;
          format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      };
      id?: string | null;
    }[];
    /**
     * Semantic-ish version identifier (e.g. "2026-07-19" or "v3.1"). Displayed on the doc page.
     */
    currentVersion: string;
    /**
     * Every published change appends a dated entry here. Enforced by a beforeChange hook when currentVersion is updated.
     */
    revisions?:
      | {
          version: string;
          date: string;
          /**
           * What changed in this revision, for the changelog view.
           */
          summary: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Counsel sign-off. The current frontend TODO flags this as unconnected — this schema makes it explicit.
     */
    legalReview?: {
      /**
       * Name of counsel or reviewing firm.
       */
      reviewedBy?: string | null;
      reviewedAt?: string | null;
      /**
       * Internal notes on the review. Not rendered publicly.
       */
      notes?: string | null;
    };
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-stats".
 */
export interface MarketStat {
  id: number;
  /**
   * Ordered list of stats shown in the market strip.
   */
  stats?:
    | {
        /**
         * The stat value as displayed, e.g. "$12.3B", "47%", "180 operators".
         */
        value: string;
        label: string;
        /**
         * The source citation. Required — no stat renders without one.
         */
        source: string;
        /**
         * Optional URL to the source. If present, the source citation renders as a link.
         */
        sourceUrl?: string | null;
        /**
         * The time period the stat covers, e.g. "2025", "Q2 2026", "12 months ending June 2026".
         */
        period: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  entries?:
    | T
    | {
        question?: T;
        answer?: T;
        status?: T;
        sourceLink?:
          | T
          | {
              label?: T;
              href?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents_select".
 */
export interface LegalDocumentsSelect<T extends boolean = true> {
  documents?:
    | T
    | {
        slug?: T;
        title?: T;
        intro?: T;
        summary?: T;
        sections?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
            };
        currentVersion?: T;
        revisions?:
          | T
          | {
              version?: T;
              date?: T;
              summary?: T;
              id?: T;
            };
        legalReview?:
          | T
          | {
              reviewedBy?: T;
              reviewedAt?: T;
              notes?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-stats_select".
 */
export interface MarketStatsSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        source?: T;
        sourceUrl?: T;
        period?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
